apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.accountService.name }}
spec:
  selector:
    app: {{ .Values.accountService.name }}
  ports:
    - port: {{ .Values.accountService.port }}
      targetPort: {{ .Values.accountService.port }}
  type: ClusterIP
