apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: "{{ .Values.clientService.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.clientService.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.clientService.name }}"
    spec:
      containers:
        - name: "{{ .Values.clientService.name }}"
          image: "{{ .Values.clientService.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.clientService.port }}
      imagePullSecrets:
        - name: ecr-secret