apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clientService.name }}
  labels:
    app: {{ .Values.clientService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.clientService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.clientService.name }}
    spec:
      containers:
        - name: {{ .Values.clientService.name }}
          image: "{{ .Values.image.registry }}/capstone/{{ .Values.clientService.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.clientService.port }}
      imagePullSecrets:
        - name: ecr-secret