apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.clientService.name }}
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
        - name: account-service
          image: {{ .Values.clientService.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.clientService.port }}
      imagePullSecrets:
        - name: ecr-secret