apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: account-service
          image: 060351708029.dkr.ecr.eu-west-1.amazonaws.com/capstone/account-service:latest
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: ecr-secret