apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SERVER_PORT: {{ .Values.apiGateway.targetPort }}

  SPRING_CLOUD_GATEWAY_ROUTES_0_ID: {{ .Values.clientService.name }}
  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "http://{{ .Values.clientService.name }}:{{ .Values.clientService.port }}"
  SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: "Path=/api/clients/**"
  SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0: "StripPrefix=1"

  SPRING_CLOUD_GATEWAY_ROUTES_1_ID: {{ .Values.accountService.name }}
  SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "http://{{ .Values.accountService.name }}:{{ .Values.accountService.port }}"
  SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: "Path=/api/accounts/**"
  SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0: "StripPrefix=1"

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.apiGateway.keycloakIssuer }}
