apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
spec:
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.targetPort }}
  type: {{ .Values.apiGateway.serviceType }}
